---
- hosts: 192.168.1.152
  become: true
  tasks:
    - name: Print OS info
      ansible.builtin.package:
        name: apache2

- hosts: 192.168.1.103
  become: true
  tasks:
    - name: Print OS info
      ansible.builtin.package:
        name: apache2
